import os
import datetime as dt

import streamlit as st
import pandas as pd

st.set_page_config(
    page_title="SETI & Exoplanet Digest — Technosignature Paper Tracker",
    page_icon="🛰️",
    layout="wide",
)

CSV_PATH = "papers.csv"
LAST_UPDATED_PATH = "last_updated.txt"


def get_last_updated_text():
    """Return a human-readable 'last updated' string.

    Prefers the explicit last_updated.txt (written by the daily update task),
    falling back to the CSV's file modification time if that file is missing.
    """
    if os.path.exists(LAST_UPDATED_PATH):
        with open(LAST_UPDATED_PATH, "r", encoding="utf-8") as f:
            raw = f.read().strip()
        try:
            parsed = dt.datetime.fromisoformat(raw)
            return parsed.strftime("%B %d, %Y")
        except ValueError:
            if raw:
                return raw

    if os.path.exists(CSV_PATH):
        mtime = os.path.getmtime(CSV_PATH)
        return dt.datetime.fromtimestamp(mtime).strftime("%B %d, %Y")

    return "unknown"

CATEGORY_INFO = {
    "Signals": "Traditional SETI, optical SETI, multi-messenger astronomy",
    "Artefacts": "Interstellar lurkers, surface artefacts",
    "Infrastructure": "Dyson spheres, starshades, city lights",
    "Propulsion methods": "Stellar engines, warp drives",
    "Other": "General exoplanet / astrobiology science (not primarily technosignature-focused)",
}


@st.cache_data
def load_data():
    df = pd.read_csv(CSV_PATH)
    return df


def main():
    df = load_data()

    st.title("SETI & Exoplanet Digest")
    st.caption(
        "A table of papers collected from the SETI & Exoplanet Digest email pipeline, "
        "classified by technosignature type."
    )
    st.info(f"🕓 Table last updated: **{get_last_updated_text()}**")

    with st.sidebar:
        st.header("Filters")

        categories = sorted(df["Technosignature Type"].unique())
        selected_categories = st.multiselect(
            "Technosignature type",
            options=categories,
            default=categories,
        )

        search_query = st.text_input("Search title or summary", "")

        st.markdown("---")
        st.markdown("### Category legend")
        for cat in ["Signals", "Artefacts", "Infrastructure", "Propulsion methods", "Other"]:
            st.markdown(f"**{cat}** — {CATEGORY_INFO[cat]}")

    filtered = df[df["Technosignature Type"].isin(selected_categories)]

    if search_query:
        q = search_query.lower()
        mask = (
            filtered["Title"].str.lower().str.contains(q, na=False)
            | filtered["Summary"].str.lower().str.contains(q, na=False)
        )
        filtered = filtered[mask]

    st.markdown(f"**{len(filtered)}** of **{len(df)}** papers shown")

    cols = st.columns(len(CATEGORY_INFO))
    for col, cat in zip(cols, CATEGORY_INFO.keys()):
        count = (df["Technosignature Type"] == cat).sum()
        col.metric(cat, count)

    st.markdown("---")

    display_df = filtered.copy().sort_values("Index")

    st.dataframe(
        display_df,
        use_container_width=True,
        hide_index=True,
        column_config={
            "Index": st.column_config.NumberColumn("#", width="small"),
            "Title": st.column_config.TextColumn("Title", width="large"),
            "Technosignature Type": st.column_config.TextColumn("Type", width="medium"),
            "PDF Link": st.column_config.LinkColumn("PDF", display_text="Open PDF"),
            "Summary": st.column_config.TextColumn("Summary", width="large"),
        },
        height=700,
    )

    st.markdown("---")
    st.caption(
        "Data source: papers gathered via the SETI & Exoplanet Digest Gmail pipeline and "
        "downloaded to Google Drive. Classifications and summaries generated by reviewing "
        "each paper's arXiv abstract."
    )


if __name__ == "__main__":
    main()
