import csv

# id -> (category, summary)
DATA = {}

def add(aid, cat, summ):
    DATA[aid] = (cat, summ)

# Chunk 1
add("2504.08363v1", "Other", "Uses clustering to find shared periodicities among CARMENES spectral activity indicators to recover stellar rotation periods for M dwarfs.")
add("2504.09087v1", "Other", "Long-term radial-velocity monitoring of giant stars to distinguish true exoplanet signals from intrinsic stellar variability.")
add("2504.10038v1", "Other", "Survey of machine learning methods applied to light curve analysis for exoplanet, variable star, and supernova detection.")
add("2504.11659v1", "Other", "JWST NIRCam coronagraphy survey of young M dwarfs probing wide-orbit sub-Jupiter mass planets and debris disks.")
add("2504.11679v1", "Other", "Models radiative flux and variability of a hot Jupiter's atmosphere for JWST and Ariel observation planning.")
add("2504.12030v1", "Other", "Shows planetary albedo is capped by the above-cloud atmosphere, complicating claims of a habitable ocean on K2-18b.")
add("2504.12118v1", "Other", "Simulates how convective mixing in giant planet atmospheres encodes information about their primordial formation state.")
add("2504.12209v1", "Other", "Reports strong evidence for a rare polar circumbinary exoplanet orbiting a pair of eclipsing brown dwarfs.")
add("2504.12267v1", "Other", "New JWST MIRI mid-infrared spectrum of K2-18b provides independent evidence for the possible biosignature gases DMS/DMDS.")
add("2504.12541v1", "Other", "Models long-term atmospheric ion escape from the two Kepler-1649 terrestrial planets under stellar wind and UV exposure.")
add("2504.12645v1", "Other", "Statistical study of blue/red H-alpha asymmetries from stellar flares on the M-dwarf YZ Canis Minoris.")
add("2504.12907v2", "Other", "Describes an improved algorithm to remove spacecraft-jitter noise from simulated Ariel exoplanet transit observations.")
add("2504.12946v2", "Other", "Reflects on JWST's early results and challenges in the search for biosignature gases on exoplanets.")
add("2504.13238v1", "Other", "Commentary noting that many exoplanet papers mislabel a standard-deviation-vs-bin-size plot as an 'Allan variance' plot.")
add("2504.13262v1", "Other", "Cross-matches TESS and K2 stellar rotation periods to quantify the reliability limits of TESS-derived rotation measurements.")
# Chunk 2
add("2504.15875v1", "Other", "Hybrid deep-learning model (CALNet) identifies thousands of new eclipsing binary stars in TESS light curves.")
add("2504.16982v1", "Other", "JWST MIRI detects thermal emission confirming WD 1856+534b as a cold, intact planet orbiting a white dwarf.")
add("2504.18219v1", "Other", "Review of current knowledge on the interior structure, magnetic fields, and formation of Uranus and Neptune.")
add("2504.16662v1", "Other", "MHD simulations predict how space weather shapes the habitability and radio emission of TRAPPIST-1e's magnetosphere.")
add("2504.14299v1", "Other", "Searches HARPS spectra of exocomets transiting Beta Pictoris for cyanogen gas, reporting only an upper limit.")
add("2504.16201v1", "Other", "Quantifies how model assumptions versus observational precision drive uncertainty in TRAPPIST-1 f's inferred water content.")
add("2504.15916v1", "Other", "Re-analysis finds no strong statistical evidence for the claimed spectral features in K2-18b's MIRI transmission spectrum.")
add("2504.17011v1", "Other", "Uses 3D simulations to isolate stellar granulation signals from spectral lines to reduce noise in exoplanet radial-velocity searches.")
add("2504.15393v1", "Other", "Keck spectroscopy sets stringent non-detection limits on infrared auroral H3+ emission from two hot Jupiters.")
add("2504.16772v1", "Other", "Models how FU Orionis stellar outbursts can vaporize and strip mass from short-period low-mass planets.")
add("2504.16236v1", "Other", "Quantum/kinetics calculations identify abiotic gas-phase routes that form dimethyl sulfide in interstellar molecular clouds.")
add("2504.14228v1", "Other", "Measures the phosphorus budget in the HD 100546 protoplanetary disk to constrain planetary habitability chemistry.")
add("2504.17585v1", "Other", "Tidal heating models suggest an unseen resonant planet may explain 55 Cancri e's nonzero orbital eccentricity.")
add("2504.13997v2", "Other", "Revises the mass and density of the puffy hot Saturn HAT-P-67 b, finding it is losing its atmosphere and will be engulfed.")
add("2504.15787v1", "Other", "Models a plasma mechanism by which the bow shock of hot Jupiter HD 189733b could generate detectable radio emission.")
# Chunk 3
add("2504.19872v1", "Other", "Revisits the 'cosmic shoreline' relation using hydrodynamic escape models to predict which rocky exoplanets retain atmospheres.")
add("2504.21852v1", "Other", "New Bayesian framework maps starspot properties on TOI-3884 using spot-crossing events during planetary transits.")
add("2504.21788v1", "Other", "Shows claimed biosignature gas detections in K2-18b's spectrum vanish once a wider space of atmospheric models is tested.")
add("2504.19709v1", "Other", "Describes SHINS, the control software for the SHARK-NIR high-contrast direct-imaging instrument at the LBT.")
add("2504.21151v1", "Infrastructure", "Shows that Dyson-swarm-like 'megaswarms' around stars are prone to rapid collisional cascades, making them short-lived technosignatures without upkeep.")
add("2504.18485v1", "Other", "Uses an iodine absorption cell to validate ESPRESSO's radial-velocity wavelength calibration at the few-cm/s level.")
add("2504.18706v1", "Other", "Applies a joint Bayesian transit detector to TESS light curves, recovering known planets and searching for new candidates.")
add("2504.18223v2", "Other", "Characterizes a rocky super-Earth and non-transiting sub-Neptune orbiting the M dwarf TOI-771 using TESS and ESPRESSO data.")
add("2504.18431v1", "Other", "Proposes 'peribiosignatures' and argues searching the edges of the habitable zone may better validate biosignature claims.")
add("2504.20158v1", "Other", "Microlensing survey finds super-Earths on Jupiter-like wide orbits are common, roughly 0.35 per star.")
add("2504.21763v1", "Other", "Shows that failing to detect one planet in a multi-planet system biases inferred spacing regularity, not mass similarity.")
add("2504.20986v1", "Other", "Finds ultra-short-period planet occurrence and system architecture evolve over Gyr timescales via tidal migration.")
add("2504.18630v1", "Other", "Finds that variable cloud cover would substantially degrade exoplanet images obtained via the solar gravitational lens.")
add("2504.18815v1", "Other", "Introduces NEXOTRANS, a hybrid Bayesian/machine-learning retrieval framework, to characterize WASP-39 b's JWST transmission spectrum.")
add("2504.19883v1", "Other", "Storm-resolving climate simulations predict lightning frequency and distribution on a tidally locked terrestrial exoplanet.")
# Chunk 4
add("2505.00064v1", "Other", "Analyzes quantum spatial demultiplexing (SPADE) for exoplanet detection, showing it stays optimal even with realistic instrumental noise.")
add("2505.00090v1", "Other", "Models how disc turbulence, metallicity, and stellar mass govern whether close-in exoplanets can form via pebble accretion.")
add("2505.00062v1", "Signals", "Builds a geometric framework linking passive radio SETI non-detections to quantitative constraints on the Fermi paradox and civilization counts.")
add("2505.03653v2", "Other", "TESS photometry reveals a resonating pulsation mode in triple-mode delta Scuti stars, marking a new post-main-sequence evolutionary indicator.")
add("2505.01496v1", "Other", "Models how a giant impact could excite long-lived, JWST-detectable seismic oscillations in a young directly-imaged giant planet like Beta Pictoris b.")
add("2505.01397v1", "Other", "High-resolution simulations find hot and warm tidally locked giant exoplanets share similar atmospheric circulation despite different temperatures.")
add("2505.03604v1", "Other", "Models a self-limiting tidal-heating feedback that can keep magma oceans molten for billions of years on the L 98-59 planets.")
add("2505.03701v1", "Other", "MHD disk simulations show low disk density stalls young planet migration near the deadzone or magnetospheric truncation radius.")
add("2505.01102v1", "Other", "Reviews ground-based high-resolution spectroscopy instrumentation and prospects for detecting O2 in Earth-analog exoplanet atmospheres.")
add("2505.03672v1", "Other", "Geochemical modeling constrains plausible volcanic water-outgassing rates that could sustain water-vapor atmospheres on the TRAPPIST-1 planets.")
add("2505.01581v1", "Other", "Proposes Ohmic heating from magnetic-field/zonal-flow interactions, rather than tides, as the source of WASP-107b's excess internal heat.")
add("2505.02818v1", "Other", "Shows combining CHES astrometry with HWO direct imaging substantially improves detection completeness for Earth-like planets.")
add("2505.01154v1", "Other", "Compiles a benchmark sample of solar-type stars with precise stellar density and surface gravity for calibrating exoplanet radius estimates.")
add("2505.01512v1", "Other", "Proposes comparing atmospheres across multiple planets in one system to define an abiotic baseline for validating biosignature claims.")
add("2505.00092v1", "Other", "Predicts the Roman Space Telescope's ability to statistically reconstruct the mass distribution of free-floating planets.")

# Chunk 5
add("2505.00064v1", "Other", "Analyzes quantum-optimal spatial demultiplexing (SPADE) for exoplanet detection under realistic noise, finding it remains the most efficient method in the sub-Rayleigh regime.")
add("2505.00090v1", "Other", "Models how pebble accretion parameters (turbulence, metallicity, stellar mass) influence the growth of close-in exoplanets within 1 au.")
add("2505.00062v1", "Signals", "Builds a geometrical/Drake-equation framework to quantify the Fermi paradox from the probability of detecting at least one extraterrestrial EM signal via passive SETI.")
add("2505.03653v2", "Other", "Reports discovery of resonating integration modes in triple-mode high-amplitude delta Scuti stars as a new stellar evolutionary phase indicator.")
add("2505.01496v1", "Other", "Shows giant impacts on young directly-imaged giant planets excite long-lived seismic oscillations detectable via photometry, illustrated with Beta Pictoris b.")
add("2505.01397v1", "Other", "Compares high-resolution atmospheric circulation simulations of tidally-locked hot and warm giant exoplanets KELT-11b and WASP-39b.")
add("2505.03604v1", "Other", "Models self-limiting tidal heating and prolonged magma oceans in the L 98-59 rocky exoplanet system via a radiation-tide-rheology feedback.")
add("2505.03701v1", "Other", "Simulates migration mechanisms of young planets in turbulent MHD protoplanetary disks, finding many planets stall near the magnetospheric truncation radius.")
add("2505.01102v1", "Other", "Reviews ground-based high-resolution spectroscopy instrumentation prospects for detecting biosignature gases like O2 in rocky exoplanet atmospheres.")
add("2505.03672v1", "Other", "Uses geochemical modeling to constrain present-day water outgassing rates as a source of secondary atmospheres on the TRAPPIST-1 planets.")
add("2505.01581v1", "Other", "Proposes Ohmic dissipation from atmospheric zonal flows and magnetic fields, rather than tidal heating alone, as the source of WASP-107b's internal heat flux.")
add("2505.02818v1", "Other", "Evaluates synergy between CHES astrometry and Habitable Worlds Observatory direct imaging for improving detection of Earth-like planets.")
add("2505.01154v1", "Other", "Compiles benchmark solar-type stars with precise mean stellar density and surface gravity measurements to calibrate exoplanet radius estimates.")
add("2505.01512v1", "Other", "Proposes a comparative multi-planet approach to define an 'abiotic baseline' for identifying genuine biosignatures across planets in the same system.")
add("2505.00092v1", "Other", "Studies the Nancy Grace Roman Space Telescope's ability to reconstruct the mass function of free-floating planets via population-level statistical inference.")

# Chunk 6
add("2505.09185v1", "Other", "Presents pilot results from the TASSIE program validating five TESS exoplanet candidates using photometry and spectroscopy from a Tasmanian observatory.")
add("2505.09307v1", "Other", "Proposes an analytical model for wavelength-dependent opposition surge effects in reflectance/emittance spectroscopy of airless rocky exoplanets.")
add("2505.09107v2", "Other", "Describes the software architecture of the Tianyu telescope pipeline, demonstrating scalable relative photometry for detecting transiting exoplanets and variable stars.")
add("2505.08883v1", "Other", "Links observable atmospheric transit spectra to the mineralogical surface composition of rocky exoplanets using equilibrium chemistry models.")
add("2505.08947v1", "Other", "Confirms TOI-5573b, a cool Saturn-like exoplanet orbiting an M-dwarf, using TESS photometry and radial velocity data.")
add("2505.09754v1", "Other", "Reviews the observed compositional diversity of low-mass exoplanets (super-Earths, mini-Neptunes) and what it reveals about planet formation.")
add("2505.08042v1", "Other", "Presents an updated orbital analysis and precise dynamical masses for the benchmark binary star system GJ 105 AC.")
add("2505.08337v1", "Other", "Introduces GRIP, an open-source data reduction toolbox for nulling interferometry used to detect exoplanets and circumstellar dust.")
add("2505.08926v1", "Other", "Reviews high-resolution spectroscopy techniques and findings for characterizing exoplanet atmospheres, from chemistry to atmospheric escape.")
add("2505.08315v1", "Other", "Introduces viper, a radial-velocity pipeline achieving high precision from optical to infrared wavelengths via telluric modelling, demonstrated with CRIRES+.")
add("2505.09578v1", "Other", "Models how disc self-gravity affects the vertical structure and warping of debris discs perturbed by an inclined planet.")
add("2505.08940v1", "Other", "Describes a data-centric machine learning approach for the NeurIPS 2024 Ariel Data Challenge on exoplanet atmosphere characterization.")
add("2505.09933v1", "Other", "Presents POSEIDON, an open-source framework for high-resolution exoplanet atmosphere retrievals, validated on WASP-77Ab and WASP-121b.")
add("2505.08863v1", "Other", "Reports JWST detection of water ice in the HD 181327 debris disk, revealing an exo-Kuiper belt analog to our solar system's icy bodies.")
add("2505.08352v1", "Other", "Describes the CHEOPS mission's ground segment systems and automation framework for exoplanet-focused photometric operations.")

# Chunk 7
add("2505.10123v1", "Other", "Confirms two hot sub-Neptune exoplanets, TOI-5800b and TOI-5817b, via radial velocity follow-up as part of the HONEI program.")
add("2505.10304v1", "Other", "Develops a retrieval framework using Love numbers and atmospheric metallicity to constrain the interior structure and core mass of hot Jupiters.")
add("2505.10621v1", "Other", "Reviews the microlensing method for detecting wide-orbit, solar-system-analog exoplanets, highlighting the upcoming Roman Space Telescope's role.")
add("2505.10574v1", "Other", "Reports the Roman Observations Time Allocation Committee's final recommendations for the Nancy Grace Roman Space Telescope's core community surveys.")
add("2505.11149v1", "Other", "Shows multi-component outgassed atmospheres on lava planets lack the runaway greenhouse thermal limit seen in pure-steam models, challenging the classical habitable zone definition.")
add("2505.10910v1", "Other", "Reports detection of limb asymmetry in WASP-94A b's atmosphere, with clouds on the cooler morning limb and clear skies on the hotter evening limb.")
add("2505.10135v1", "Other", "Searches Kepler data for close-in non-transiting substellar companions, identifying 88 candidate systems useful for studying star-planet tidal/magnetic interactions.")
add("2505.12152v1", "Other", "Develops a validated sulfur-inclusive C/H/O/N chemical network to model photochemistry and abundance profiles in exoplanet atmospheres like WASP-39b and WASP-107b.")
add("2505.10647v1", "Other", "Models the interior and climate of Venus Zone planet TOI-2285 b, finding temperate scenarios consistent with its known properties despite a likely steam atmosphere.")
add("2505.12945v1", "Other", "Presents gr8stars, a homogeneous spectroscopic survey and public spectral library of bright FGKM dwarf stars relevant to exoplanet host characterization.")
add("2505.12148v1", "Other", "Revises the chemical network modeling helium absorption in exoplanet atmospheres to include photoelectron-driven processes, applied to GJ 436 b.")
add("2505.11147v1", "Other", "Demonstrates a high-throughput holographic grating design for high-resolution narrowband spectroscopy, relevant to exoplanet radial velocity and atmospheric instruments.")
add("2505.13295v1", "Other", "Reports a directly imaged planetary-mass candidate companion at a very wide separation (730 au) discovered by the Young Suns Exoplanet Survey.")
add("2505.13602v1", "Other", "Characterizes evening/morning limb composition and cloud variation on WASP-107 b using JWST, and models stellar contamination effects on the measurements.")
add("2505.10539v1", "Other", "Conducts an agnostic search across 650 molecules in K2-18 b's JWST spectrum, finding weak evidence for a few biogenic gases beyond the previously reported DMS.")

# Chunk 8
add("2505.14317v1", "Other", "Reports discovery of five new massive exoplanets around evolved giant stars HD 87816, HD 94890, and HD 102888 via CORALIE radial-velocity monitoring.")
add("2506.14744v1", "Signals", "Explores using real-time astronomical alert brokers (ZTF, upcoming LSST) to conduct optical and temporal SETI searches, including planetary transit zone and SETI Ellipsoid methods.")
add("2506.14737v1", "Signals", "Describes SETI@home's second-stage analysis of 14 years of Arecibo radio data, covering RFI removal and ranking of technosignature candidates for follow-up with FAST.")
add("2506.14718v1", "Signals", "Describes SETI@home's distributed-computing front-end data acquisition and processing pipeline for radio technosignature searches at Arecibo Observatory (1998-2020).")
add("2506.14691v1", "Other", "Presents a benchtop laser mass spectrometer analog of the Mars MOMA instrument for validating organic biosignature detection ahead of the Rosalind Franklin rover mission.")
add("2505.16543v1", "Other", "Uses photochemical modeling to show Venus's abiotic mesospheric ozone arises from an unknown chemical pathway, warning of ozone biosignature false positives on Venus-like exoplanets.")
add("2506.13459v1", "Signals", "Reports a Breakthrough Listen radio technosignature search around 27 eclipsing TESS exoplanets using Parkes telescope data, finding no signals beyond terrestrial RFI.")
add("2506.11690v1", "Other", "Reviews the diversity of exoplanetary environments where life could plausibly exist, including alternative solvents, cloud biospheres, and metal-ion requirements for biochemistry.")
add("2506.21790v1", "Other", "Shows reflected-light spectroscopy with the Habitable Worlds Observatory could detect exposed land on exo-Earths, ruling out waterworld O2 biosignature false positives.")
add("2505.23279v1", "Other", "Models how nitrous oxide abundance affects the O2-O3 relationship across different host star types, complicating the use of ozone as an oxygen biosignature proxy.")
add("2506.02730v1", "Signals", "Proposes using language models to detect 'generative reactivity' in noise-like signals (e.g., whale/bird vocalizations) as a novel complementary SETI signal-screening method.")
add("2506.16351v1", "Signals", "White paper reviewing the rationale, challenges, and possible technosignatures for high-energy SETI searches in X-rays, gamma rays, and neutrinos.")
add("2505.16231v1", "Other", "Uses atmospheric retrievals to assess how detectable chemical disequilibrium biosignatures (available Gibbs free energy) are for a modern Earth-like exoplanet analog.")
add("2505.13692v1", "Other", "Presents lab experiments showing UV radiation from stellar flares alters and degrades photochemical hazes on sub-Neptune exoplanets.")
add("2505.13705v1", "Other", "Develops a new chemical network (ChaiTea) to test whether thermodynamic equilibrium can be established in the warm, dense inner regions of planet-forming disks.")

# Chunk 9
add("2507.00765v1", "Other", "Models chemical equilibration between primordial atmospheres and magma oceans, showing most sub-Neptunes lose their accreted water and don't qualify as Hycean planets.")
add("2507.11587v1", "Signals", "White paper on SETI post-detection readiness, recommending NASA investment in interdisciplinary infrastructure for handling a potential technosignature detection.")
add("2507.00165v1", "Other", "Proposes searching for 'prebiosignature gases' with the Habitable Worlds Observatory to test theories of abiogenesis even where detectable life is rare.")
add("2507.03819v1", "Other", "Proposes HWO coronagraph imaging polarimetry surveys to detect photosynthetic biosignatures via linear/circular polarization signatures of biopigments on exoplanets.")
add("2507.03819v2", "Other", "Proposes HWO coronagraph imaging polarimetry surveys to detect photosynthetic biosignatures via linear/circular polarization signatures of biopigments on exoplanets.")
add("2507.11587v1", "Signals", "White paper on SETI post-detection readiness, recommending NASA investment in interdisciplinary infrastructure for handling a potential technosignature detection.")
add("2507.12622v1", "Other", "Uses new JWST/NIRSpec transit spectra of K2-18 b to robustly detect CH4 and CO2, establishing a water-rich interior while finding only marginal DMS/CH3SH signals.")
add("2507.14771v1", "Other", "Determines the near-UV to near-infrared wavelength coverage HWO needs to contextualize O2/CH4 biosignatures and rule out false positives on rocky exoplanets.")
add("2507.17790v1", "Signals", "Argues for rebalancing NASA funding toward extraterrestrial intelligence/technosignature research, citing the funding gap relative to biosignature missions like HWO.")
add("2507.18665v1", "Other", "Lists NASA's Exoplanet Exploration Program annual science gaps needed to advance future exoplanet characterization and biosignature missions.")
add("2508.00076v1", "Other", "Trains a 1D CNN to retrieve molecular abundances and biosignatures from simulated reflection spectra of evolving Earth-like exoplanets for future HWO observations.")
add("2508.00249v1", "Signals", "Uses radio source count and SETI survey field limits to constrain the abundance of artificial radio broadcast populations from inhabited galaxies, including Kardashev Type III limits.")
add("2508.01281v1", "Other", "Reports a near-infrared high-resolution atmospheric retrieval of brown dwarf HR 7672 B using the REACH/Subaru instrument, identifying H2O, FeH, and cloud opacity.")
add("2508.01354v1", "Signals", "Presents gamma/hadron separation simulations for the Dark100/PANOSETI Cherenkov telescope array, part of an optical/high-energy SETI-linked instrument used for dark matter and transient searches.")
add("2508.02746v1", "Other", "White paper identifying high-confidence agnostic biosignature targets (biopolymers, homochirality, chiral metabolism) for future astrobiology missions to Martian mid-latitude ice.")
add("2506.21790v2", "Other", "Shows reflected-light spectroscopy with the Habitable Worlds Observatory could detect exposed land on exo-Earths, ruling out waterworld O2 biosignature false positives.")

# Chunk 10
add("2508.09167v1", "Artefacts", "Introduces the Loeb Scale, a 0-10 classification system extending the Torino Scale to systematically evaluate interstellar objects for potential technosignatures/artificial origin.")
add("2508.05548v1", "Signals", "Describes development and deployment of PANOSETI's Fresnel-lens optical/UHE gamma-ray telescopes, part of the Dark100 array combining SETI and astroparticle science.")
add("2508.15425v1", "Signals", "Analyzes NASA Deep Space Network transmission logs to identify optimal SETI target-selection and scheduling strategies for detecting civilizations using similar deep-space networks.")
add("2508.10657v1", "Signals", "Re-analyzes archival Ohio SETI data to revise the location, intensity, and frequency of the famous 1977 Wow! Signal, supporting an astrophysical rather than artificial origin.")
add("2509.09654v1", "Signals", "Reports a FAST radio telescope targeted SETI search for narrowband technosignatures toward 7 nearby active planet-hosting stars, with no credible detections and new transmitter power limits.")
add("2508.05961v2", "Other", "Reanalyzes JWST data of K2-18b using independent methods, finding MIRI instrumental systematics undermine the reported DMS/DMDS biosignature evidence.")
add("2508.20215v1", "Other", "Reports citizen-astronomer photometric observations showing continued long-term activity decline of Jupiter-family Comet 103P/Hartley 2.")
add("2508.14126v1", "Other", "Presents lunar farside radio array concepts for detecting exoplanet magnetospheres via low-frequency radio emission to prioritize biosignature follow-up targets.")
add("2508.18287v1", "Signals", "Proposes the Adaptive Communication Framework, a crisis-communication protocol calibrated to the Loeb Scale for managing public messaging around a potential technosignature discovery.")
add("2509.09780v1", "Other", "Reports progress toward demonstrating ultraviolet coronagraphy on a vacuum testbed to support HWO's detection of ozone biosignatures.")
add("2508.16825v1", "Artefacts", "Reviews interstellar objects as targets for technosignature searches, outlining four classes of technosignatures suited to ISO follow-up ahead of the LSST era.")
add("2508.08628v1", "Signals", "Conducts an optical SETI survey of 2,821 stars using archival HARPS spectra, narrowing thousands of laser-like spectral spikes down to 3 unexplained candidates warranting follow-up.")
add("2508.20169v1", "Other", "Presents the design of VIPER, a high-resolution VIPA-based spectrograph for detecting helium-line atmospheric escape and oxygen biosignatures in exoplanets.")
add("2508.08699v1", "Other", "Detects solar-like asteroseismic oscillations in 196 bright TESS stars, expanding the benchmark sample useful for future HWO and PLATO target characterization.")
add("2509.06310v1", "Signals", "Reports a FAST radio telescope narrowband SETI search of the TRAPPIST-1 system, finding no technosignature candidates and setting new transmitter power limits.")

# Chunk 11
add("2510.00082v1", "Artefacts", "Explores solar system technosignatures of self-replicating interstellar probes, proposing the Moon as a manufacturing base with detectable isotopic and artefact signatures.")
add("2509.20718v1", "Signals", "Proposes a hybrid SETI signaling strategy using the Galactic Center as a spatial reference and extragalactic bursts like GRB 221009A as temporal markers to narrow the search parameter space.")
add("2511.06139v1", "Signals", "Presents a firefly-inspired model for detecting technosignatures via structural signal dissimilarity from natural backgrounds, tested on pulsar data.")
add("2511.05660v1", "Other", "Reviews current estimates and limitations in determining eta-Earth, the occurrence rate of Earth-like planets in habitable zones of Sun-like stars.")
add("2511.05427v1", "Other", "Uses VLA radio observations to place upper limits on stellar/coherent radio emission from the K2-18 system, constraining its magnetic activity environment.")
add("2510.14776v1", "Other", "Models UV flux and atmospheric pressure scenarios for TOI-700 d, finding habitability plausible while noting hazes both hinder and aid biosignature detectability.")
add("2511.00525v1", "Other", "Introduces molecular diversity of amino/fatty acids, measured via ecodiversity metrics, as a new class of biosignature distinguishing biotic from abiotic samples.")
add("2510.17907v1", "Artefacts", "Describes four low-cost methods for detecting extraterrestrial probes/artefacts in the Solar System, demonstrating a proof-of-concept search using Earth's shadow and ZTF data.")
add("2510.14506v1", "Signals", "Presents a revised IAA Declaration of Principles, updating SETI post-detection protocols for responding to a potential extraterrestrial signal detection.")
add("2509.23632v1", "Signals", "Argues advanced civilizations' rapid technological acceleration shrinks SETI's detection window, proposing technology-agnostic searches beyond narrowband radio/optical signals.")
add("2510.26483v1", "Signals", "Uses 28.8 years of radial velocity data to rule out the proposed giant planet Calpamos around zeta2 Reticuli, the suspected source of a claimed technological signal.")
add("2509.22301v1", "Infrastructure", "Simulates direct-imaging phase curve signatures of hypothetical starshades around HWO target stars, proposing them as a detectable technosignature of advanced civilizations.")
add("2510.08636v1", "Other", "Summarizes a NASA/SETI Institute workshop on developing Foundation Models for astrobiology applications like biosignature characterization and mission operations.")
add("2511.08624v1", "Other", "Analyzes stellar UV spectra across star types to assess which are thermodynamically favorable for abiogenesis via photon-dissipative structuring, favoring F/G/K stars.")
add("2509.25173v2", "Other", "Presents the first reflectance spectra of atmospheric microorganism biopigments as a novel atmospheric biosignature for detecting life in planetary clouds.")

# Chunk 12
add("2512.09970v1", "Signals", "Proposes the Eschatian Hypothesis: the first confirmed technosignature detection is likely to come from an atypically 'loud,' possibly unstable or terminal-phase civilization.")
add("2511.20231v1", "Signals", "Uses the Besancon Galactic Model to simulate stellar 'bycatch' in Breakthrough Listen radio SETI surveys, deriving tighter statistical limits on extraterrestrial transmitter prevalence.")
add("2512.15809v1", "Signals", "Applies a DBSCAN machine learning algorithm to mitigate residual radio frequency interference in FAST-SETI archival technosignature survey data, improving removal rate and speed.")
add("2511.21085v2", "Signals", "Reports a FAST multibeam narrowband technosignature search of five Milky Way globular clusters, yielding a null result and new EIRP limits on radio beacons in dense stellar systems.")
add("2511.20329v1", "Infrastructure", "Uses ten future Earth technosphere scenarios to propose a stepwise technosignature search strategy, finding industrial/agricultural atmospheric gas pairs (e.g. CO2+NO2) detectable by HWO and LIFE.")
add("2512.10277v1", "Other", "Models reflection and thermal emission spectra of Earth-analog atmospheres under varying surface conditions to assess biosignature detectability with HWO and LIFE mission concepts.")
add("2512.07924v1", "Infrastructure", "Proposes a probabilistic microlensing framework to detect Dyson Sphere-like swarm structures around primordial black holes as a technosignature of advanced civilizations.")
add("2511.16714v1", "Other", "Advocates for studying planet formation conditions and bulk planetary chemistry as key drivers of long-term habitability in exoplanetary systems.")
add("2512.19763v1", "Signals", "Reports a Breakthrough Listen radio technosignature search of interstellar object 3I/ATLAS at its closest approach using the Green Bank Telescope, with a nondetection down to 100 mW.")
add("2512.04122v1", "Other", "Examines four historical astrobiology controversy case studies (Mars canals, Viking, Venus phosphine, BLC1) to draw lessons for responsible handling of future life-detection claims.")
add("2512.18903v1", "Signals", "Outlines a plan for ESO to conduct optical SETI searches for artificial laser communication using extreme multiplexity spectroscopic facilities by the 2040s.")
add("2512.18142v1", "Signals", "Reports a radio technosignature search of interstellar object 3I/ATLAS using the Allen Telescope Array, finding no credible signals and setting EIRP limits of 10-110 W.")
add("2511.20329v2", "Infrastructure", "Uses ten future Earth technosphere scenarios to propose a stepwise technosignature search strategy, finding industrial/agricultural atmospheric gas pairs (e.g. CO2+NO2) detectable by HWO and LIFE.")
add("2511.21085v1", "Signals", "Reports a FAST multibeam narrowband technosignature search of five Milky Way globular clusters, yielding a null result and new EIRP limits on radio beacons in dense stellar systems.")
add("2512.11383v1", "Other", "Detects a strong directional correlation between galaxy gas angular momenta and the primordial tidal field, confirming tidal torque theory predictions for the early universe.")

# Chunk 13
add("2602.17736v1", "Signals", "Uses Bayesian inference to show that undetected past technosignature contacts within a few hundred light-years would require implausibly large numbers of emitters, suggesting searches should extend thousands of light-years.")
add("2603.00203v1", "Propulsion methods", "Models the orbital dynamics of ultra-large stellar engines and Dyson bubbles, showing non-uniform reflector designs can achieve passive stability, informing what such technosignatures might look like.")
add("2601.20620v1", "Other", "Reviews 12 years of NCCR PlanetS contributions to climate modeling, atmospheric retrieval, and instrumentation for characterizing terrestrial exoplanet biosignatures.")
add("2602.11046v1", "Other", "Describes early architecture design concepts, system modeling, and trade studies for NASA's Habitable Worlds Observatory flagship mission.")
add("2601.08390v1", "Other", "Uses neutron and X-ray computed tomography on a Martian meteorite to reveal a macroscopic crustal water reservoir of hydrated iron oxyhydroxides on early Mars.")
add("2601.07297v1", "Infrastructure", "Uses WISE/CatWISE mid-infrared photometry of nearby galaxies to place upper limits on galaxy-scale Dysonian waste-heat technosignatures, constraining Kardashev Type III civilization prevalence.")
add("2601.08883v1", "Other", "Assesses HWO measurement requirements for detecting surface biosignatures like photosynthetic pigments on potentially habitable exoplanets across Earth's geologic history.")
add("2601.21946v2", "Artefacts", "Critically reexamines claims of glinting artificial-object technosignatures in pre-Sputnik POSS1 photographic plates, finding the reported anomalies and correlations do not hold up under scrutiny.")
add("2602.09553v1", "Signals", "Reports a coordinated VLA and MeerKAT narrowband radio technosignature search of Hycean candidate K2-18b, finding no artificial signals and setting the first interferometric limits for this planet type.")
add("2601.06386v1", "Other", "NASA DARES white paper outlining HWO Living Worlds Working Group biosignature science cases and identifying key astrobiology research gaps needed ahead of the mission.")
add("2601.20902v1", "Other", "Advocates for adding spectropolarimetric capability to HWO's instrument suite to better characterize exoplanet clouds, atmospheres, and surfaces.")
add("2601.21946v1", "Artefacts", "Critically reexamines claims of glinting artificial-object technosignatures in pre-Sputnik POSS1 photographic plates, finding the reported anomalies and correlations do not hold up under scrutiny.")
add("2601.14630v1", "Signals", "Reports a FAST radio SETI search for kHz-wide periodic signals from five nearby stars, finding no convincing detections and setting stringent EIRP limits on periodic beacons.")
add("2601.20620v2", "Other", "Reviews 12 years of NCCR PlanetS contributions to climate modeling, atmospheric retrieval, and instrumentation for characterizing terrestrial exoplanet biosignatures.")
add("2602.15171v1", "Artefacts", "Rebuts a critique of earlier POSS1 photographic-plate technosignature studies, defending the statistical methodology behind the reported Earth-shadow deficit and anomaly clusters.")

# Chunk 14
add("2603.07333v1", "Signals", "Proposes 'Broadband SETI,' repurposing extensive non-SETI radio/optical surveys to constrain the prevalence of nearby communicative civilizations and alien probes.")
add("2603.07333v2", "Signals", "Proposes 'Broadband SETI,' repurposing extensive non-SETI radio/optical surveys to constrain the prevalence of nearby communicative civilizations and alien probes.")
add("2603.27598v1", "Other", "Develops a GC-MS/MS method to quantify 56 prebiotic molecules in Titan and Martian analog materials, identifying amino acids as robust biosignature candidates.")
add("2603.18250v1", "Other", "Models how gamma-ray bursts could act as evolutionary filters limiting complex life near the galactic center, discussing implications for biosignature and technosignature searches.")
add("2603.11017v1", "Other", "Uses photochemical simulations of Mars-like exoplanet atmospheres to reassess how much abiotic O2/O3 can accumulate via CO2 photolysis, revising earlier false-positive estimates downward.")
add("2603.18923v1", "Other", "Tests abiotic formation pathways for DMS/DMDS on K2-18b, finding hydrocarbons like C2H6 are a plausible alternative explanation and modeling sulfur haze formation in sub-Neptune atmospheres.")
add("2603.22491v1", "Other", "Applies Lotka-Volterra ecological models to simulate microbial population dynamics in hycean-world water columns, exploring biosignature interpretation for such planets.")
add("2603.01032v1", "Signals", "Develops a forward-inverse method exploiting planetary-rotation Doppler drift to reconstruct the spatial distribution of radio transmitters on an unresolved Earth-like technosignature source.")
add("2603.24485v1", "Other", "Describes the proposed Canadian POET microsatellite mission for tri-band photometric transit characterization of exoplanets, including ultracool dwarf habitable-zone searches.")
add("2603.22602v1", "Other", "Uses Enceladus's ice shell morphology and ocean circulation modeling to constrain the salinity and heat dissipation rate of its subsurface ocean.")
add("2603.28977v1", "Other", "A satirical April Fools paper proposing a SETI search for star-powered food-warming objects in a hypothetical planetary 'Flavor Zone,' concluding such objects are undetectable.")
add("2603.09321v1", "Other", "White paper proposing a UK-led near-infrared integral field spectrograph for the HWO coronagraph to help detect exoplanet biosignatures like simultaneous O2 and CH4.")
add("2603.28895v1", "Other", "A satirical April Fools paper modeling exoplanet atmospheric 'monster deterrents' (garlic-like sulfur gases, silver hazes, salt aerosols) as folklore-inspired spectral signatures.")
add("2603.19023v1", "Signals", "Reports a FAST radio technosignature search of interstellar object 3I/ATLAS across four observing epochs, finding no credible signals and using Bayesian inference to constrain hypothetical transmitters.")
add("2603.11146v1", "Other", "Assesses the astrometric precision needed for HWO to measure ~10% mass precision for directly imaged Earth-analog exoplanets, key for interpreting their atmospheric biosignatures.")

# Chunk 15
add("2604.26925v1", "Other", "Determines the spectral resolving power HWO needs across visible/UV/near-IR bands to reliably detect biosignature gases in Earth-like atmospheres through geologic time.")
add("2604.08993v1", "Signals", "Presents signal-to-noise calculations for detecting Earth's O2 biosignature versus an enhanced hydrogen iodine technosignature, finding the latter too weak to realistically constrain with current concepts.")
add("2604.07920v1", "Signals", "Reports the first lunar farside radio SETI search for periodic technosignatures using Chang'E-4 low-frequency data, finding no credible artificial signal candidates.")
add("2604.24988v1", "Signals", "Introduces an open-source browser-based simulator modeling relativistic signal propagation effects for SETI and exoplanet applications across 62 confirmed Milky Way exoplanets.")
add("2604.21886v1", "Infrastructure", "Summarizes a workshop on 'Dyson Minds'—hypothetical post-biological intelligences powered by supermassive black holes—and observational strategies for detecting such megastructure technosignatures.")
add("2604.20896v1", "Artefacts", "Examines the philosophical/epistemic status of 'candidate technosignature' classifications like Level 4 on the Loeb Scale for anomalous interstellar objects, arguing it justifies methodological escalation, not belief.")
add("2604.06807v1", "Signals", "Uses TESS light curves to test the hybrid ring coordinated-signaling strategy anchored to GRB 221009A, finding candidate brightenings but attributing them to instrumental effects.")
add("2604.12104v1", "Other", "Reviews outgassing/plume signatures of active moons (Io, Europa, Enceladus, Triton) and Io-like exomoons, and their potential for biosignature investigation.")
add("2605.04187v1", "Other", "Models how planetary climate states and seasonal obliquity affect reflectance spectra and biosignature detectability for future direct-imaging missions like HWO.")
add("2604.16746v1", "Other", "Makes the case for designing HWO to detect stellar coronal mass ejections, which can deplete ozone and threaten biosignature gases on orbiting exoplanets.")
add("2604.16746v2", "Other", "Makes the case for designing HWO to detect stellar coronal mass ejections, which can deplete ozone and threaten biosignature gases on orbiting exoplanets.")
add("2603.29700v1", "Other", "A satirical April Fools paper claiming JWST detection of cannabinoid molecules in K2-18b's atmosphere and proposing a 'Cannabis Habitable Zone' framework.")
add("2604.18749v1", "Other", "Reviews Laser Ionisation Mass Spectrometry capabilities for detecting biosignatures (microstructures, isotope fractionation, organics) on future Solar System astrobiology missions.")
add("2604.14276v1", "Other", "Presents photonic lantern devices combining spectroscopy and wavefront sensing to help HWO achieve the deep contrast needed for exoplanet biosignature characterization.")
add("2604.13774v1", "Signals", "Models civilization collapse-recovery duty cycles over 1000 years, arguing the absence of detected extraterrestrial technosignatures may reflect low-duty-cycle civilizations rather than the rarity of intelligent life.")

# Chunk 16
add("2605.05408v2", "Signals", "Reports results from ten years of UCLA's narrowband radio SETI search with the Green Bank Telescope across 70,000+ stars, all candidates confirmed anthropogenic, setting stringent transmitter prevalence limits.")
add("2605.08569v1", "Other", "Develops a relativistic mode-sum framework for neutron-star tidal response during binary inspiral, unrelated to exoplanets or SETI.")
add("2605.21093v1", "Signals", "A 118-page comprehensive review organizing proposed technosignatures by spatial scale, from Earth's orbit through the Solar System to stellar, galactic, and extragalactic signals.")
add("2605.05408v1", "Signals", "Reports results from ten years of UCLA's narrowband radio SETI search with the Green Bank Telescope across 70,000+ stars, all candidates confirmed anthropogenic, setting stringent transmitter prevalence limits.")
add("2605.10212v1", "Signals", "Proposes a hierarchical framework using SKA-era wide-field surveys and VLBI follow-up to detect planetary-scale broadband radio leakage technosignatures, extending Kardashev Type I detection to 100 pc.")
add("2605.10646v1", "Other", "Surveys mineral reflectance databases to identify non-biological minerals that mimic the vegetation red edge, a key surface biosignature feature HWO will search for.")
add("2605.19252v1", "Other", "Introduces elemental stoichiometry patterns in small-molecule chemical space as a new ecological biosignature framework for distinguishing biotic from abiotic samples in planetary mission data.")
add("2605.15337v1", "Other", "Develops a framework for evaluating biosignature candidates against abiotic baselines on ocean worlds like Enceladus, showing current uncertainties can produce false negative life-detection claims.")
add("2605.06072v1", "Infrastructure", "Develops a Gaia-based 'crystallization index' quantifying ordered structure in globular cluster dynamics, providing a metric for prioritizing clusters for technosignature-oriented follow-up.")
add("2605.16674v1", "Other", "Models detection biases showing the first remotely detected exoplanet biosignature via JWST or HWO may be an atypical outlier rather than representative of habitable planets generally.")
add("2605.17098v1", "Artefacts", "Applies the Loeb-Turner alpha-slope photometric technosignature test to trans-Neptunian object archival data, finding calibration systematics rather than genuine self-luminous anomalies among Kuiper Belt objects.")
add("2605.12647v1", "Other", "Compiles a catalog of stellar ages for 659 high-priority HWO target stars to help interpret evolutionary trends in exoplanet biosignatures.")
add("2605.19482v1", "Signals", "Identifies methodological synergies between radio technosignature searches and ultra-high-energy neutrino experiments, proposing shared RFI-mitigation and anomaly-ranking techniques for SETI pipelines.")
add("2605.20305v1", "Other", "Reviews the technological innovations and scientific potential of the Extremely Large Telescope, including its capability to characterize Earth-like exoplanet atmospheres for biosignatures.")
add("2605.20305v2", "Other", "Reviews the technological innovations and scientific potential of the Extremely Large Telescope, including its capability to characterize Earth-like exoplanet atmospheres for biosignatures.")

# Chunk 17
add("2605.29811v1", "Artefacts", "Develops a meteorite-calibrated Bayesian framework to search archival stellar abundance data for chemical technosignatures indicating artificially processed material, finding few strong candidates.")
add("2606.00463v2", "Artefacts", "Proposes a multi-pronged technosignature strategy emphasizing Solar System searches for extraterrestrial artefacts (SETA), including micron-scale 'Arkhipov particles' in lunar regolith, to constrain the Fermi Paradox.")
add("2606.00463v4", "Artefacts", "Proposes a multi-pronged technosignature strategy emphasizing Solar System searches for extraterrestrial artefacts (SETA), including micron-scale 'Arkhipov particles' in lunar regolith, to constrain the Fermi Paradox.")
add("2606.10108v1", "Other", "Presents the KISS workshop study report on the LIFE mid-infrared nulling interferometer concept for detecting climate gases and biosignatures on temperate terrestrial exoplanets.")
add("2606.06692v1", "Signals", "Develops a parametric stellar exclusion model using Gaia DR3 data to flag stars unlikely to host complex life, refining target prioritization for SETI surveys.")
add("2606.06692v2", "Signals", "Develops a parametric stellar exclusion model using Gaia DR3 data to flag stars unlikely to host complex life, refining target prioritization for SETI surveys.")
add("2606.08373v1", "Artefacts", "Reviews prospects for detecting passive technosignatures that persist without upkeep, including specular reflections, X-ray binary lens flares, and surviving Dyson swarm dust as relics of extinct civilizations.")
add("2606.04304v1", "Signals", "Reports an all-sky ultra-narrowband imaging technosignature search with OVRO-LWA at decametric wavelengths, finding no extraterrestrial signals among three candidates after detailed re-imaging.")
add("2606.05451v1", "Other", "Uses photochemical modeling to show how uncertain UV spectra of ultracool M dwarfs like TRAPPIST-1 create degeneracies that complicate interpreting CH4/CO/O2/O3 biosignatures on Archean-analog planets.")
add("2606.05364v1", "Other", "Advocates for a coordinated Hubble UV spectroscopy program of high-priority HWO target stars to constrain radiation environments needed for interpreting future biosignature observations.")
add("2605.23739v1", "Signals", "Introduces a wavelet-based machine learning pipeline for narrowband radio technosignature detection in FAST observations of 33 exoplanet systems, improving candidate localization and filtering.")
add("2606.00574v1", "Signals", "Presents a coherence-based framework for using Vera Rubin Observatory LSST photometric data to flag technosignature and astrobiology candidates as structured departures from natural variability patterns.")
add("2606.04105v1", "Other", "Ranks HWO Exoplanet Exploration Program target stars by their likelihood of hosting a temperate terrestrial planet, using simulated planetary system occurrence-rate models.")

# Chunk 18
add("2607.07413v1", "Signals", "Models how technological acceleration shrinks the window during which a civilization's technosignatures overlap with our detection capability, advocating broadband, technology-agnostic search strategies.")
add("2607.03619v1", "Infrastructure", "Uses archival Gaia, WISE, and optical/near-IR imaging to identify background contamination in Project Hephaistos Dyson Sphere candidate M-dwarfs, ruling out several as false positives.")
add("2606.13797v1", "Artefacts", "Reviews current limits on Solar System technosignatures, including probes and surface artefacts from other civilizations, finding only crude upper limits given uneven search completeness.")
add("2607.03106v1", "Other", "White paper identifying research priorities for phototrophic biosignatures, including diverse light-harvesting pigments and photosynthesis pathways detectable via direct imaging missions.")
add("2606.24458v1", "Other", "Introduces an agnostic, thermodynamics-based machine learning model of photosynthetic habitability, expanding the Photosynthetic Habitable Zone estimate beyond Earth-centric assumptions.")
add("2607.07592v1", "Signals", "Argues technosignature searches implicitly search for 'polluting' civilizations reflecting Earth's colonial societies, and proposes reconsidering technosignatures through an Indigenous studies lens.")
add("2606.28437v1", "Artefacts", "Proposes 'noosemiotics,' the study of structured traces ('noosignatures') that minds leave on physical or signal media, using material culture as a primary test bed for astrobiology.")
add("2607.01666v1", "Signals", "Reports a periodic radio technosignature search of interstellar object 3I/ATLAS using FAST and tensor decomposition methods, finding no credible artificial periodic signals.")
add("2606.24028v1", "Artefacts", "Models interstellar transport of micron-scale engineered particulate debris to the lunar regolith, using a null detection to constrain past galactic civilizations' particulate technosignature output.")
add("2606.24028v3", "Artefacts", "Models interstellar transport of micron-scale engineered particulate debris to the lunar regolith, using a null detection to constrain past galactic civilizations' particulate technosignature output.")
add("2606.27664v1", "Signals", "Proposes a dual-burst geometrical coordination scheme using two cosmological transients as Schelling-point anchors to narrow the sky search area for concurrent interstellar signaling.")
add("2606.27565v1", "Signals", "Discusses how the Square Kilometre Array's sensitivity and field of view will advance frequency-domain radio technosignature searches, emphasizing machine learning and multi-wavelength follow-up.")
add("2607.07781v1", "Infrastructure", "Introduces Stellar J-Harvesting, a technosignature where an engineered system extracts a star's rotational angular momentum, and conducts a pilot slow-rotator search in Kepler field stars.")
add("2606.11102v1", "Signals", "Reviews the final decades of the Ohio SETI Program (Big Ear), which discovered the Wow! Signal and amassed a still largely unexplored radio archive of narrowband transient events.")
add("2607.07182v1", "Signals", "Reports a combined ATA and VLA radio technosignature search of the LTT3780 exoplanet system, including candidate Hycean world LTT3780c, finding no candidate signals.")

# Chunk 19
add("2607.28121v1", "Other", "Uses the LIFE mid-infrared interferometer simulator to show how retrieved atmospheric CO2/CH4/NH3 can distinguish the oxidation state of rocky exoplanet mantles.")
add("2607.21683v1", "Other", "White paper arguing the LIFE mid-infrared interferometer can detect a wider range of biosignatures at lower concentrations than HWO, including methane as a key false-positive discriminator.")
add("2608.19328v1", "Other", "Models how M-dwarf age-dependent UV flux alters photochemistry and biosignature gas abundances (CH4, O3) in Pre-Industrial and Archean Earth-like atmospheres, risking misinterpretation of ozone features.")
add("2607.25762v1", "Signals", "Describes the proposed LFT3 lunar farside radio telescope mission, designed to exploit the interference-free environment for technosignature searches, transients, and other radio science.")
add("2607.25701v1", "Infrastructure", "Follows up seven Project Hephaistos Dyson-sphere candidate M-dwarfs with new photometry/spectroscopy, finding no clear explanation for their infrared excess but noting some may be background contamination.")
add("2607.07787v1", "Other", "Uses Gaia astrometry and Galactic chemical evolution models to trace exoplanet host stars' birth radii and radial migration, identifying reference populations for future habitability searches.")
add("2607.24527v1", "Other", "Models how growing lunar satellite traffic will increasingly contaminate the radio-quiet lunar farside environment needed for future technosignature and transient searches like LFT3.")
add("1804.04727v2", "Propulsion methods", "Shows that chemical rockets can still achieve escape velocity from rocky Super-Earths up to 10 Earth masses, beyond which nuclear propulsion would be required for spaceflight.")
add("2608.12458v1", "Infrastructure", "Applies stellar population synthesis modeling to 129 nearby galaxies searching for galaxy-spanning Dyson sphere waste heat, finding no detections and setting population-level upper limits.")
add("2608.16060v1", "Propulsion methods", "Searches Gaia DR3 astrometric accelerations of 406,984 nearby stars for signatures of operating stellar engines, finding no candidates and setting population upper limits.")
add("2608.18275v1", "Signals", "Describes the COSMIC system's high-frequency radio technosignature search on the VLA, using Doppler drift detection on Gaia-catalogued exoplanet host stars.")
add("2607.23651v1", "Signals", "Describes BLUSE, Breakthrough Listen's autonomous commensal technosignature survey system on the MeerKAT array, which has processed over 1.2 million pointings since 2022.")
add("2607.13867v1", "Signals", "Overviews the SKAO 'Cradle of Life' science cases spanning star/planet formation, exoplanet auroral radio emission, and systematic technosignature searches across the SKA's frequency range.")
add("2608.11294v1", "Other", "Presents 70 HWO science cases developed by NASA's START working groups spanning galaxy evolution, elemental chemistry, solar system science, and living worlds.")

if __name__ == "__main__":
    print("Unique IDs in DATA:", len(DATA))

# Chunk 5 fix - duplicate versions already classified
add("2606.00463v1", "Artefacts", "Proposes a multi-pronged technosignature strategy emphasizing Solar System searches for extraterrestrial artefacts (SETA), including micron-scale 'Arkhipov particles' in lunar regolith, to constrain the Fermi Paradox.")
add("2606.00463v3", "Artefacts", "Proposes a multi-pronged technosignature strategy emphasizing Solar System searches for extraterrestrial artefacts (SETA), including micron-scale 'Arkhipov particles' in lunar regolith, to constrain the Fermi Paradox.")

# Chunk 5 (corrected - actual IDs)
add("2505.07091v1", "Other", "Uses X-ray diffraction and Raman spectroscopy to identify a new hydrogen-rich hydrate phase at pressures up to 104 GPa, relevant to the interiors of icy giant planets.")
add("2505.03927v1", "Signals", "Applies machine learning anomaly detection to Breakthrough Listen radio observations of hundreds of stars, visually inspecting ~20,000 top candidates with no technosignature surviving scrutiny.")
add("2505.05948v1", "Other", "Systematically searches 308 TESS giant planet candidates for exoplanetary ring systems, finding no conclusive detections and setting upper limits on ring occurrence rates.")
add("2505.06228v1", "Other", "Applies a new machine learning pipeline to determine the composition of exoplanetary material accreted onto five helium-atmosphere white dwarfs, finding compositions broadly consistent with chondritic material.")
add("2505.06358v1", "Other", "Reports discovery of a small inner super-Earth in the young multi-planet TOI-2076 system and updates the system's age using rotation and lithium diagnostics.")
add("2505.07760v1", "Other", "Uses simulated direct-imaging observations to show clouds generally enhance the detectability of O2 and O3 biosignatures on terrestrial exoplanets, aiding future HWO observations.")
add("2505.07602v1", "Other", "Searches WISE 12-micron photometry for exozodiacal dust around stars within 10 parsecs, finding candidate excesses are more likely brown dwarf photosphere effects than true exozodi.")
add("2505.04106v1", "Other", "Derives the eccentricity distribution of warm sub-Saturn exoplanets from TESS transit light curves, finding a population of highly eccentric planets suggestive of high-eccentricity migration.")
add("2505.03881v1", "Other", "Develops an alternate spectral normalization method to reduce star-spot contamination noise in transit spectroscopy searches for biosignature molecules around M-dwarfs.")
add("2505.05571v1", "Other", "Compares JWST data reduction algorithms for jump detection and ramp fitting, finding a new likelihood-based method improves NIRISS/SOSS exoplanet transmission spectra accuracy.")
add("2505.03723v1", "Other", "Uses 3D climate models with interactive photochemistry to simulate how stellar flares and energetic particles affect the atmosphere and climate of tidally-locked TRAPPIST-1e-like exoplanets.")
add("2505.06013v1", "Other", "Models how billions of years of atmospheric escape enrich metal abundances in warm super/sub-Neptune atmospheres, complicating interpretation of their formation history from observed compositions.")
add("2505.04413v1", "Other", "Uses the new SANSAR retrieval framework to reanalyze HD 209458 b's HST and JWST transmission spectra, finding combined optical-to-infrared data needed for robust metallicity constraints.")
add("2505.05680v1", "Other", "Shows sweeping secular resonances from evolving stellar oblateness can misalign inner planets, reducing the observed rate of multi-planet transiting systems like Kepler-619.")
add("2505.05260v1", "Other", "Uses 15 years of radial velocity and photometric monitoring to conclusively rule out a previously claimed giant planet around the K giant star 42 Draconis, attributing signals to stellar oscillations.")
